apiVersion: v1
kind: Pod
metadata:
  name: kube-bench
spec:
  hostPID: true
  containers:
    - name: kube-bench
      image: aquasec/kube-bench:latest
      args: ["--benchmark", "cis-1.23", "--json"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
          readOnly: true
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
        - name: etc-systemd
          mountPath: /etc/systemd
          readOnly: true
        - name: usr-bin
          mountPath: /usr/bin
          readOnly: true
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
          readOnly: true
  volumes:
    - name: var-lib-etcd
      hostPath:
        path: /var/lib/etcd
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: etc-systemd
      hostPath:
        path: /etc/systemd
    - name: usr-bin
      hostPath:
        path: /usr/bin
    - name: var-lib-kubelet
      hostPath:
        path: /var/lib/kubelet
  restartPolicy: Never